#spring:
#  main:
#    web-application-type: none
#    banner-mode: off
#  ai:
#    mcp:
#      server:
#        name: stdio-mcp-server-demo
#        version: 1.0.0
#
#logging:
#  pattern:
#    console:
#  file:
#    name: F:\myDoc\2024.4\wangyiying-homework\20260228\ai-agent\spring-ai-mcp-server-demo\spring-ai-mcp-server.demo.log

spring:
  ai:
    mcp:
      server:
        name: sse-mcp-server-demo
        version: 1.0.0
server:
  port: 8081